# basic build file

sudo: false
language: java
jdk: oraclejdk8
before_install:
  - echo "MAVEN_OPTS='-Xmx2g'" > ~/.mavenrc
script:
  - mvn -f org.eclipse.gef.releng/pom.xml -P MARS_4_5.target package

